name: Data Pipeline on Self-Hosted Runner

on:
  push:
    branches: [ main ]

jobs:
  pipeline:
    # This tells GitHub to only run this job on your private VM
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Spark Pipeline
        env:
          SPARK_HOME: /opt/spark
          # Define the path to your virtualenv here for easy updates
          PYTHON_PATH: /home/ubuntu/spark-env/bin/python 
        run: |
          # 1. Ensure absolute paths are used
          # 2. Use the virtual environment Python directly
          # 3. $GITHUB_WORKSPACE is where the code was checked out
          
          echo "Starting Pipeline execution..."
          $PYTHON_PATH $GITHUB_WORKSPACE/process_data.py